name: character
description: A new Flutter project.
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=3.1.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_modular: ^6.3.2
  flutter_bloc: ^8.1.3
  equatable: ^2.0.5
  dio: ^5.3.3
  shimmer: ^3.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  mocktail: ^1.0.1
  bloc_test: ^9.1.4
  test: ^1.24.3

flutter:
  uses-material-design: true
